[FIX] edit sample
CCExtractor/sample-platform pull request #558
Opened 2021-06-03 04:47 UTC by kvshravan

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that another pull request for this purpose does not exist.
- [ ] I have considered, and confirmed that this submission will be valuable to others.
- [ ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ ] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Fix #554

2021-06-03 04:52 UTC, kvshravan commented
One of the reasons we never came across this error is because there are no tests for edit_sample function.

2021-06-03 05:31 UTC, thealphadollar commented
> One of the reasons we never came across this error is because there are no tests for edit_sample function.

Oh! Do you think adding a test in the PR will be helpful?

2021-06-03 06:16 UTC, canihavesomecoffee requested changes
This is not a good fix. The CommonSampleForm class is there with a reason.

Wrt tests, it'd be nice to have some indeed.

2021-06-03 06:16 UTC, canihavesomecoffee commented on mod_sample/forms.py
> +    notes = TextAreaField('Notes', [DataRequired(message='Notes are not filled in')])
This is duplication of the fields that are in CommonSampleForm.

I'd rather see the offending fields in that class moved to the appropriate class (take a look at the history and you'll see when they've been added and for what reason).

2021-06-03 13:30 UTC, kvshravan commented
> > One of the reasons we never came across this error is because there are no tests for edit_sample function.
> 
> Oh! Do you think adding a test in the PR will be helpful?

Yes I will be adding a test.

2021-06-04 14:48 UTC, canihavesomecoffee submitted a review, later dismissed
LGTM

2021-06-04 15:37 UTC, thealphadollar approved these changes
A small minor edit. See if you want to include it. 

Rest, LGTM.

2021-06-04 15:37 UTC, thealphadollar commented on mod_upload/forms.py
> +    report = SelectField('Do you want to report Issue on GitHub?', choices=[('n', 'No'), ('y', 'Yes')])
```suggestion
    report = SelectField('Do you want to report an issue on GitHub?', choices=[('n', 'No'), ('y', 'Yes')])
```

2021-06-04 15:50 UTC, merged