[IMPROVEMENT] Rename "kvm" table name to "gcp_instance"
CCExtractor/sample-platform pull request #710
Opened 2022-09-27 23:51 UTC by Tarun-Arora

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

---

This PR renames the "kvm" table to "gcp_instance" and attempts to solve https://github.com/CCExtractor/sample-platform/issues/695 issue.

However, this is not an independent PR, it is based on #703. We could then merge the two migrations using `flask db merge` command if required.

2022-10-01 13:03 UTC, thealphadollar requested changes
Great work, Tarun. I've requested one minor change.

Also, I think we have mentioned KVM in the mod_upload/controllers.py as well, can you please check that (https://github.com/CCExtractor/sample-platform/blob/d5254363c32b138e1b56ae71c4519181f06efc0e/mod_upload/controllers.py#L254-L255)

2022-10-01 14:49 UTC, thealphadollar approved these changes
LGTM. Thanks for working on the comments, Tarun.

2022-10-02 17:57 UTC, canihavesomecoffee approved these changes

2022-10-02 17:57 UTC, merged

2022-10-02 17:57 UTC, canihavesomecoffee commented
Nice job :)