[IMPROVEMENT] Do not run the CI if it's a draft pull request
CCExtractor/sample-platform pull request #775
Opened 2023-04-13 08:46 UTC by ArchitBhonsle

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

A simple two line change that also checks whether the pull request under question is not a draft request.

2023-04-13 08:58 UTC, canihavesomecoffee commented
Can you add a unit test for it as well? :)

2023-04-14 20:16 UTC, canihavesomecoffee commented
@ArchitBhonsle can you check why it fails to apply pydocstyle?

2023-05-25 17:36 UTC, ArchitBhonsle commented
Sorry for the ugly force push. It had been a long time since I worked on this and the progress wasn't that significant so I just nuked it.

2023-05-25 17:40 UTC, ArchitBhonsle commented
I decided to simply `pass` draft PRs. This preserves the original flow of dumping `{'msg': 'EOL'}`. Is that OK or should it return something else?

https://github.com/ArchitBhonsle/sample-platform/blob/43cf1bb96cdf5555a294a9be0c7ee9552e9af42a/mod_ci/controllers.py#L890-

2023-05-25 17:46 UTC, ArchitBhonsle commented
Oh never mind. This implementation has a bug. It checks whether a PR is draft first. This causes an issue for a **closed draft**. The running tasks are not cancelled as the function never reaches the "closed" `elif`.

2023-05-26 04:14 UTC, thealphadollar reviewed
The PR looks good to me. Thanks for the contribution, Archit.

Let's add/update unit tests and then we can merge it 🚢

2023-05-26 10:50 UTC, thealphadollar requested changes
Hey! This looks good to me. Would you mind adding few new tests for draft:true PRs?

2023-05-26 10:54 UTC, ArchitBhonsle commented
Yup I was just looking at the WebHook documentation and checking if I'm missing anything. Looks like I am. I think `ready_for_review` should also trigger the CI.

2023-05-26 16:11 UTC, thealphadollar approved these changes
LGTM! Thanks for adding the tests, Archit 🚢 

Let us see why the tests are failing.

2023-05-26 16:13 UTC, ArchitBhonsle commented
Yup I understand why my tests are failing. I didn't add the arguments passed by the decorators. But not sure why the other tests are. I'll look into it.

2023-05-27 07:43 UTC, Tarun-Arora commented
@ArchitBhonsle we should also stop the tests if possible when the PR is just marked as start.
You may also refer to PR #792 for this and unittests as well. And we can merge these PRs.

2023-05-27 07:48 UTC, ArchitBhonsle commented
@Tarun-Arora that would be when the PR is `converted_to_draft` right?

2023-05-27 12:52 UTC, ArchitBhonsle commented
The tests were failing because I added `draft` at the wrong level. `payload->draft` instead of `payload->pull_request->draft` 🫠

2023-05-27 16:01 UTC, canihavesomecoffee approved these changes

2023-05-27 16:01 UTC, merged

2023-05-27 16:01 UTC, canihavesomecoffee commented
Nice work, thanks :+1:

2023-05-27 16:07 UTC, Tarun-Arora commented on mod_ci/controllers.py
>                  tests = Test.query.filter(Test.pr_nr == pr_nr).all()
@ArchitBhonsle We should also update the message on line 919. "PR closed", "PR marked as draft".