[IMPROVEMENT] Deprecate mod_deploy module and update Deployment pipeline workflow
CCExtractor/sample-platform pull request #842
Opened 2023-08-02 07:55 UTC by Tarun-Arora

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

---

Closes #836 

Please remove the GitHub webhook for `/deploy` endpoint from the repository settings

2023-08-02 08:53 UTC, Tarun-Arora commented on decorators.py
> +            repo = git.Repo(search_parent_directories=True)
Yes true, but this is also basically looking up of a file
We can put this with `g.github` globals, then we would have to lookup only once?

(Actually I wanted to remove the overhead of maintaining a file for build commit hash)

2023-08-05 09:18 UTC, thealphadollar approved these changes
LGTM.

2023-08-05 09:18 UTC, thealphadollar commented on utility.py
> +                g.log.info(f"Request type {request.method} detected")
[nitpik] Make the logs lowercase.

2023-08-05 09:18 UTC, thealphadollar commented on utility.py
> +    return hmac.compare_digest(mac.hexdigest(), github_signature)
```suggestion

    return hmac.compare_digest(mac.hexdigest(), github_signature)
```

2023-08-05 09:18 UTC, thealphadollar commented on utility.py
> +    return False
```suggestion

    return False
```

2023-08-05 09:18 UTC, thealphadollar commented on utility.py
> +    return decorator
```suggestion
            return f(*args, **kwargs)

        return decorated_function

    return decorator
```

2023-08-05 09:21 UTC, thealphadollar requested changes
Let us add tests for the new changes and merge the PR afterwards.

2023-08-06 05:32 UTC, thealphadollar submitted a review, later dismissed

2023-08-08 16:24 UTC, thealphadollar approved these changes

2023-08-08 16:24 UTC, thealphadollar commented
@canihavesomecoffee Can you please review before we merge it?

2023-08-08 18:07 UTC, canihavesomecoffee approved these changes

2023-08-08 18:34 UTC, merged